import { Router, type IRouter } from "express";
import healthRouter from "./health";
import productsRouter from "./products";
import ordersRouter from "./orders";
import paystackRouter from "./paystack";
import usersRouter from "./users";
import adminRouter from "./admin";
import autologinRouter from "./autologin";
import proxyRouter from "./proxy";
import storageRouter from "./storage";
import fxRouter from "./fx";
import siteSettingsRouter from "./siteSettings";
import trackingRouter from "./tracking";
import trustRouter from "./trust";
import toolAssignmentsRouter from "./toolAssignments";
import homepageContentRouter from "./homepageContent";
import staffAuthRouter from "./staffAuth";
import blogPostsRouter from "./blogPosts";
import blogTaxonomyRouter from "./blogTaxonomy";
import blogMediaRouter from "./blogMedia";
import blogSeoRouter from "./blogSeo";
import blogCommentsRouter from "./blogComments";
import blogSettingsRouter from "./blogSettings";
import blogRedirectsRouter from "./blogRedirects";
import seoGeneratorRouter from "./seoGenerator";
import systemConfigRouter from "./systemConfig";
import paymentSettingsRouter from "./paymentSettings";
import aiConfigRouter from "./aiConfig";
import emailRouter from "./email";
import featureFlagsRouter from "./featureFlags";
import couponsRouter from "./coupons";
import referralsRouter from "./referrals";
import authManagerRouter from "./authManager";
import systemHealthRouter from "./systemHealth";
import storageAdminRouter from "./storageAdmin";
import cacheMaintenanceRouter from "./cacheMaintenance";
import emergencyRecoveryRouter from "./emergencyRecovery";
import protectedDataRouter from "./protectedData";
import deploymentSafetyRouter from "./deploymentSafety";
import backupsRouter from "./backups";
import restoresRouter from "./restores";
import dbIntegrityRouter from "./dbIntegrity";
import productRecoveryRouter from "./productRecovery";
import paymentRecoveryRouter from "./paymentRecovery";
import customerRecoveryRouter from "./customerRecovery";
import migrationReadinessRouter from "./migrationReadiness";
import { deviceTrackingMiddleware } from "../middlewares/deviceTracking";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(fxRouter);
router.use(siteSettingsRouter);
router.use(trackingRouter);
router.use(trustRouter);
router.use(toolAssignmentsRouter);
router.use(homepageContentRouter);
router.use(staffAuthRouter);
router.use(blogPostsRouter);
router.use(blogTaxonomyRouter);
router.use(blogMediaRouter);
router.use(blogSeoRouter);
router.use(blogCommentsRouter);
router.use(blogSettingsRouter);
router.use(blogRedirectsRouter);
router.use(seoGeneratorRouter);
router.use(productsRouter);
router.use(ordersRouter);
router.use(paystackRouter);
router.use(deviceTrackingMiddleware);
router.use(usersRouter);
router.use(adminRouter);
router.use(systemConfigRouter);
router.use(paymentSettingsRouter);
router.use(aiConfigRouter);
router.use(emailRouter);
router.use(featureFlagsRouter);
router.use(couponsRouter);
router.use(referralsRouter);
router.use(authManagerRouter);
router.use(systemHealthRouter);
router.use(storageAdminRouter);
router.use(cacheMaintenanceRouter);
router.use(emergencyRecoveryRouter);
router.use(protectedDataRouter);
router.use(deploymentSafetyRouter);
router.use(backupsRouter);
router.use(restoresRouter);
router.use(dbIntegrityRouter);
router.use(productRecoveryRouter);
router.use(paymentRecoveryRouter);
router.use(customerRecoveryRouter);
router.use(migrationReadinessRouter);
router.use(autologinRouter);
router.use(proxyRouter);

export default router;
